version: '3.2'

services:
  redis:
    build:
      context: "${PWD}/redis/"
      dockerfile: redis.Dockerfile
    container_name: redis_docker # 컨테이너 이름 설정
    ports:
      - "6379:6379"
    volumes:
#      - type: bind
#        source: "/Users/Shared/data/redis:/data" # -v 옵션 (다렉토리 마운트 설정)
#        read_only: true
      - "${PWD}/redis/data:/data"
    networks:
      - project


  web:
    build:
      context: "${PWD}/ruby/"
      dockerfile: ruby.Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3600:3000'
    volumes:
      - "${PWD}/ruby:/app"
    environment:
      RAILS_ENV: development
#    volumes_from:
#      - datastore
#    depends_on:
#      - db
#    links:
#      - db
#      - db:database
#      - db:mysql
#    extends:
#      file: ./docker/mysql/password.yml
#      service: password

networks:
  project:
    driver: bridge

volumes:
  reids: